name: flutter_chopper_blog
description: Demo app for the Sembast DB libary
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.1.0
  chopper: ^3.0.3
  connectivity: ^0.4.9+5
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator: ^7.1.0
  chopper_generator: ^3.0.5

flutter:
  uses-material-design: true
                                      